# Generated by Django 3.0.4 on 2020-03-22 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travel_notes_app', '0002_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='destination',
            name='text',
            field=models.CharField(max_length=70),
        ),
    ]
